### ISSUE TITLE
Quarto installation not found when click on render in Visual Studio Code

### ISSUE THREAD

**Issue by acuenya** [quarto-dev/quarto-vscode#63]
Error message
"Quarto installation not found"
"Please install Quarto CLI before rendering documents"

When I click on Render button  in VS Code  (see code below)
- Windows 10 pro 64 bits
- Installed  quarto-1.0.38-win.msi
- Installed VS Code extention Quarto v1.32.0
- Path c:\Program Files\Quarto\bin
- In c:\Program Files\Quarto\bin there are two files a) quarto.cmd and b) quarto.js

CODE----------------------------------------
---
title: "Quarto Basics"
format:
  html:
    code-fold: true
jupyter: python3
---

For a demonstration of a line plot on a polar axis, see @fig-polar.

```{python}
#| label: fig-polar
#| fig-cap: "A line plot on a polar axis"

import numpy as np
import matplotlib.pyplot as plt

r = np.arange(0, 2, 0.01)
theta = 2 * np.pi * r
fig, ax = plt.subplots(
  subplot_kw = {'projection': 'polar'} 
)
ax.plot(theta, r)
ax.set_rticks([0.5, 1, 1.5, 2])
ax.grid(True)
plt.show()
```

**Comment by jjallaire** [comment]
What terminal/shell are you using? It is Git Bash or PowerShell or something else?

**Comment by acuenya** [comment]
The error appears when I click on Render button in Visual Studio Code.
I use Power Shell or CMD

**Comment by jjallaire** [comment]
For some reason Quarto is not on the PATH visible to Visual Studio Code (the Quarto installer puts it on the PATH by default so not sure what is going on here)

**Comment by acuenya** [comment]
Thank you anyway

**Comment by acuenya** [comment]
It may be a problem in the Quarto extension for VS Code for Windows

**Comment by dragonstyle** [comment]
Have you restarted VSCode since installing Quarto? It could be as simple as the terminal sessions in vscode needing to reload their paths.

**Comment by acuenya** [comment]
I restarted it many times. I unistalled Quarto, VS Code extention, restarted the notebook, installed everything again and restarted Windows and nothing changed, the same error.

**Comment by jjallaire** [comment]
What happens if you type `quarto check` in the VS Code terminal? 

What about `$Env:Path` in PowerShell within VS Code?

**Comment by acuenya** [comment]
-> Typing `quarto check` in the VS Code terminal I got:
'findstr' is not recognized as an internal or external command,
operable program or batch file.
-> Typing `$Env:Path` in PowerShell withing VS Code I got (Quarto\bin is in the path):
c:\masm32\bin;C:\Program Files\Calibre2\;C:\Program Files\Git\cmd;C:\Users\cueny\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\cueny\AppData\Local\Programs\Python\Python39\;C:\Users\cueny\AppData\Local\Microsoft\WindowsApps;C:\Users\cueny\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\cueny\AppData\Roaming\TinyTeX\bin\win32;C:\Program Files\Quarto\bin;C:\Users\cueny\AppData\Local\Programs\Quarto\bin

**Comment by jjallaire** [comment]
Okay, we fixed something related the findstr issue in v1.1. This is currently available as a pre-release here: https://quarto.org/docs/download/prerelease.html

Could you try again with v1.1?

**Comment by acuenya** [comment]
Same errors.
I uninstalled Quarto 1.0; Installed 1.1; restarted VS Code; restarded Windows and everything is the same

**Comment by JMLuther** [comment]
Same issues as OP (also on Windows 10 Pro)- except quarto check in VSCode terminal installation is OK (OK report for basic MD render, py3 install, and Jupyter engine render).
I also installed dev Quarto 1.1.113 and restarted all.
Have entered quarto path into the extension path 
When attempting to render .qmd file using Render button in VScode still get "Quarto installation Not Found"

**Comment by JMLuther** [comment]
Also confirmed that Quarto bin folder is on PATH
Maybe related?: Works in RStudio, but I am using the RStudio packaged Quarto. Originally had issues getting the standalone installation to work there - solved once I uninstalled and used the bundled version with RStudio.

**Comment by pat-s** [comment]
After updating to v1.1 I am also facing the same issue (macOS, v1.1.113).
I realized it was caused by the `quarto-dev` formula, most likely some path issue there.

Uninstalling the homebrew formula and reinstalling the official `.pkg` solved the issue.

Reinstalling the `quarto-dev` formula reproduced the issue.

**Comment by lyledanley** [comment]
Having the same issue. @pat-s can you expand on how you did what you did? Uninstalling teh homebrew formula and reinstalling the official `.pkg`?

**Comment by pat-s** [comment]
Most likely caused by https://github.com/rundel/homebrew-quarto-cli/issues/37. Reinstalling dev after the fix should do it.

**Comment by lyledanley** [comment]
> Most likely caused by [rundel/homebrew-quarto-cli#37](https://github.com/rundel/homebrew-quarto-cli/issues/37). Reinstalling dev after the fix should do it.

Unfortunately, didn't work. Still unable to render in VS Code IDE. When I use the python terminal and run `quarto render document_name.qmd` from command line, executes fine. Wondering if it's a VS Code extension issue as well.

**Comment by JMLuther** [comment]
I saw that related issue was fixed with the Quarto CLI update.
however- I am still having the same issue even after update to v1.1.145.

**Comment by jpmorr** [comment]
For anyone struggling with this bug, it has been solved with the latest update of both the extension and cli tool. See here https://github.com/quarto-dev/quarto-cli/issues/2143#issue-1352196375 .

**Comment by acuenya** [comment]
Still have an error (a problem with Jupiter engine render) - See below
1) Installed new version 1.1.165
2) Update VS Code extention
3) Reload VS Code
4) Restart VS Code
----------------------------------------------
When I run `quarto check` I got:
PS C:\Users\cueny\OneDrive\Documentos\Cursos\Python\Utility> quarto check

[>] Checking Quarto installation......OK
      Version: 1.1.165
      Path: C:\Users\cueny\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.13 (Conda)
      Path: C:/Users/cueny/AppData/Local/R-MINI~1/python.exe
      Jupyter: 4.11.1
      Kernels: python3

(|) Checking Jupyter engine render....Traceback (most recent call last):
  File "C:\Users\cueny\AppData\Local\Programs\Quarto\share\jupyter\jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "C:\Users\cueny\AppData\Local\Programs\Quarto\share\jupyter\notebook.py", line 16, in <module>
    import nbformat
ModuleNotFoundError: No module named 'nbformat'
[>] Checking Jupyter engine render....OK

And when I click on Render button in VS Code:

PS C:\Users\cueny\OneDrive\Documentos\Cursos\Python\Utility> quarto preview demo.qmd --no-browser --no-watch-inputs
Starting python3 kernel...Traceback (most recent call last):
  File "C:\Users\cueny\AppData\Local\Programs\Quarto\share\jupyter\jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "C:\Users\cueny\AppData\Local\Programs\Quarto\share\jupyter\notebook.py", line 16, in <module>
    import nbformat
ModuleNotFoundError: No module named 'nbformat'
PS C:\Users\cueny\OneDrive\Documentos\Cursos\Python\Utility> conda activate base
conda : The term 'conda' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, 
verify that the path is correct and try again.
At line:1 char:1
+ conda activate base
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (conda:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by jjallaire** [comment]
The fact that `conda activate base` is failing points to a problem with your underlying conda installation (VS Code is attempting to activate conda when the terminal starts up but is failing to do so)

**Comment by JMLuther** [comment]
just FYI The update to quarto fixed the issue for me.
I did have similar issues with python as @acuenya, which was unrelated to Quarto. Fixed by removing old python and julia kernels (see also resolution of issue #1643 and [this SO answer](https://stackoverflow.com/questions/73270420/file-not-found-error-when-verifying-quarto-installation))
